version: '2.1'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:${GITLAB_CE_VERSION}'
    restart: always
    container_name: gitlab
    hostname: '${GITLAB_HOST}'
    # command: /bin/bash
    environment:
      - 'TZ=${TZ}'
      - 'VIRTUAL_HOST=${GITLAB_HOST},${REGISTRY_HOST}'
      - VIRTUAL_PORT=80
      - 'LETSENCRYPT_HOST=${GITLAB_HOST},${REGISTRY_HOST}'
      - 'LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}'
      #- USERMAP_UID=988
      # - USERMAP_GID=1001
    ports:
      - '${GITLAB_SSH_IP}:${GITLAB_SSH_PORT}:22'
      - '81:80'
      - '8443:443'
    volumes:
      - './volumes/config:/etc/gitlab'
      - './volumes/logs:/var/log/gitlab'
      - './volumes/data:/var/opt/gitlab'
    depends_on:
      - redis-gitlab
      - postgres-gitlab
    networks:
      - default
  runner:
    image: 'gitlab/gitlab-runner:${GITLAB_RUNNER_VERSION}'
    restart: always
    container_name: gitlab_runner
    depends_on:
      - gitlab
    ports:
      - '8093:8093'
    environment:
      - 'CI_SERVER_URL=https://${GITLAB_HOST}/'
    volumes:
      - './volumes/runner:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
  postgres-gitlab:
    image: 'postgres:${POSTGRES_VERSION}'
    restart: always
    container_name: gitlab_postgresql
    environment:
      - POSTGRES_USER=gitlab
      - POSTGRES_DB=gitlabhq_production
    volumes:
      - './volumes/postgres:/var/lib/postgresql/data'
  redis-gitlab:
    image: 'redis:${REDIS_VERSION}'
    restart: always
    container_name: gitlab_redis
    command:
      - '--loglevel warning'
    volumes:
      - './volumes/redis:/var/lib/redis'
